spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,gateway"
  endpoint:
    gateway:
      access: unrestricted
